### ISSUE TITLE
issue after new update,

### ISSUE THREAD

**Issue by Laern2Do** [Yutsuten/anki-lifedrain#75] opened 2020-06-03 12:14 UTC
i receive this error when attempting to change the setting through option >life drain (main screen)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-06-02 19:21:29

Caught exception:
Traceback (most recent call last):
  File "aqt\deckconf.py", line 316, in accept
  File "<C:\Users\xxx\Documents\Anki\decorator.pyc:decorator-gen-96>", line 2, in saveConf
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 660, in repl
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\715575551\main.py", line 150, in <lambda>
    DeckConf.saveConf, lambda *args: lifedrain.deck_settings_save(args[0]),
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 112, in deck_settings_save
    self._deck_settings.old_save_form_data(settings, set_deck_conf)
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\715575551\settings.py", line 370, in old_save_form_data
    set_deck_conf(conf)
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\715575551\deck_manager.py", line 77, in set_deck_conf
    self._bar_info[deck_id]['maxValue'] = conf['maxLife']
KeyError: 1563908965878

**Comment by Yutsuten** [comment] 2020-06-03 12:17
Thank you for reporting the issue.
I was able to reproduce this error here, I'll release a fix for this soon.

**Comment by Yutsuten** [comment] 2020-06-03 12:28
I released a new version with a fix.
Can you update the add-on again and check if the problem was solved for you?

**Closed** 2020-06-03 12:30 UTC
Labels: bug, critical

**Comment by Laern2Do** [comment] 2020-06-03 12:34
yeep, it doesnt through me that error anymore, however, when I attempt to change some values, it doesn't save after existing,

for example, if I change the damage value to any number, say 0, from the initial 5, this wont save when I close the config box (same with maximum life)

but since we it not necessary after the next release, I assume it wont matter :)?

Thx for ur speedy response!

**Comment by Yutsuten** [comment] 2020-06-03 12:43
> for example, if I change the damage value to any number, say 0, from the initial 5, this wont save when I close the config box (same with maximum life)

The damage value indeed is not saved unless you check the Enable Damage checkbox. But another options does work for me. Are you sure the options aren't being saved?

My Anki version is the latest (2.1.26), so if it really does not save for you, it may be an incompatibility with old Anki versions.

If that's the case, I can rollback people with Anki <= 2.1.22 to the previous version.

**Comment by Laern2Do** [comment] 2020-06-03 12:48
sorry i should have kept the convo here, i create a new issue for this one, and it indeed doesn't seem to work for me, apology for running you around :/
