### ISSUE TITLE
damage value is not save after new update for v2.1.22

### ISSUE THREAD

**Issue by Laern2Do** [Yutsuten/anki-lifedrain#77] opened 2020-06-03 12:46 UTC
when I attempt to change the damage values in setting, it doesn't save after existing, (enable damage box check, or uncheck). this occur in both the main screen setting, and overview setting

for example, if I change the value to any number, say 0, from the initial 5, this wont save when I close the config box

Thx for ur speedy response!

**Comment by Yutsuten** [comment] 2020-06-03 12:57
Is that only for damage value?

**Comment by Laern2Do** [comment] 2020-06-03 13:05
main screen, it actually the current life that doesn't work now
![image](https://user-images.githubusercontent.com/63658303/83639754-c4821100-a570-11ea-942c-2643387685e4.png)

overview screen, only the damage value doesn't work
![image](https://user-images.githubusercontent.com/63658303/83639861-f004fb80-a570-11ea-9ec8-2d6ee2344f39.png)

**Comment by Yutsuten** [comment] 2020-06-03 13:12
I downloaded Anki 2.1.22 here and I'm not being able to reproduce your issue...
To change the damage value, please check the Enable damage checkbox.

![checkbox](https://i.imgur.com/ld9ivGI.png)

Anyway, I need to disable the damage field when the checkbox is not checked...

**Comment by Laern2Do** [comment] 2020-06-03 13:26
yeep, it will not take 0 as a value for me for damage, check or uncheck (overview screen and main), other numbers work fine 1,2,3,.. etc

also the current life is will not change, doesn't matter what value I enter (in the main screen only, the overview work fine), the workaround for this is if I exist and open the app again

**Comment by Laern2Do** [comment] 2020-06-03 13:37
since changing the setting is being remove from option, it doesn't matter :), I will just work with the overview screen, the setting is save there and if i unchecked the damage box, i should still be getting what I'm asking for. so no worry... sorry for the mess. 

thanks so much!

**Comment by Yutsuten** [comment] 2020-06-03 13:38
> yeep, it will not take 0 as a value for me for damage, check or uncheck (overview screen and main), other numbers work fine 1,2,3,.. etc

Okaay, the problem was with the number 0, it is falsy in python. I'll fix it.

**Comment by Yutsuten** [comment] 2020-06-03 13:46
> also the current life is will not change, doesn't matter what value I enter (in the main screen only, the overview work fine)

To reproduce this you have to open the options from the main screen twice. I wasn't doing that. I'll look for a fix for this one too.
In the future I may add a new option for Life Drain in the main screen, so it is better to fix the problem as soon as possible.

>the setting is save there and if i unchecked the damage box, i should still be getting what I'm asking for. so no worry... sorry for the mess.

No worries! Thank you very much for the patience to explain me those issues! I certainly wouldn't notice those by myself.

**Comment by Laern2Do** [comment] 2020-06-03 13:59
yeeper, thx you for being patience as well :)

**Comment by Yutsuten** [comment] 2020-06-03 14:11
I updated a new release to AnkiWeb.
Can you check if it fixes the issues for you?

**Comment by Laern2Do** [comment] 2020-06-03 14:14
looking good, thx so much!

**Comment by Yutsuten** [comment] 2020-06-03 14:14
Nice!!

**Closed** 2020-06-03 14:15 UTC
Labels: bug
